version: '3.9'

services:
  web:
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapicompose:fastapicompose@db:5432/fastapicompose
    depends_on:
      - db
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      # - POSTGRES_NAME=fastapicompose
      - POSTGRES_USER=fastapicompose
      - POSTGRES_PASSWORD=fastapicompose
      - POSTGRES_DB=fastapicompose

volumes:
  postgres_data: